# Generated by Django 3.2.6 on 2021-08-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210828_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='csv',
            new_name='csv_file',
        ),
    ]
